import type { ListingData } from '@/components/listings/listing-card'

export const MOCK_LISTINGS: ListingData[] = [
  {
    id: '1',
    title: 'Two lovable golden retrievers in sunny LA',
    city: 'Los Angeles', state: 'CA', country: 'US',
    startDate: '2026-04-23', endDate: '2026-05-03',
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=70'],
    type: 'FREE', isPaid: false,
    pets: [{ type: 'DOG', name: 'Buddy' }, { type: 'DOG', name: 'Max' }],
    owner: { firstName: 'Sandra', lastName: 'K', averageRating: 4.9, totalSits: 12 },
    isNew: true, isLowApplications: true, matchScore: 92,
    currentApplicants: 2, maxApplications: 10,
  },
  {
    id: '2',
    title: 'Cosy San Francisco apartment with two cats',
    city: 'San Francisco', state: 'CA', country: 'US',
    startDate: '2026-03-14', endDate: '2026-03-22',
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=70'],
    type: 'FREE', isPaid: false,
    pets: [{ type: 'CAT', name: 'Luna' }, { type: 'CAT', name: 'Mochi' }],
    owner: { firstName: 'Ali', lastName: 'B', averageRating: 5.0, totalSits: 8 },
    isNew: false, isLowApplications: false, matchScore: 87,
    currentApplicants: 5, maxApplications: 10,
  },
  {
    id: '3',
    title: 'Beachfront Malibu home — paid sit, no pets',
    city: 'Malibu', state: 'CA', country: 'US',
    startDate: '2026-05-01', endDate: '2026-05-15',
    photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=70'],
    type: 'PAID', isPaid: true, price: 120, currency: 'USD',
    pets: [],
    owner: { firstName: 'James', lastName: 'R', averageRating: 4.8, totalSits: 3 },
    isNew: true, isLowApplications: true, matchScore: 78,
    currentApplicants: 1, maxApplications: 10,
  },
  {
    id: '4',
    title: 'Charming Pasadena home with dog & garden',
    city: 'Pasadena', state: 'CA', country: 'US',
    startDate: '2026-04-10', endDate: '2026-04-20',
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=70'],
    type: 'FREE', isPaid: false,
    pets: [{ type: 'DOG', name: 'Rosie' }],
    owner: { firstName: 'Maria', lastName: 'G', averageRating: 4.7, totalSits: 19 },
    isNew: false, isLowApplications: false, matchScore: 85,
    currentApplicants: 7, maxApplications: 10,
  },
  {
    id: '5',
    title: 'Modern Santa Monica condo — senior cat',
    city: 'Santa Monica', state: 'CA', country: 'US',
    startDate: '2026-04-05', endDate: '2026-04-18',
    photos: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=70'],
    type: 'FREE', isPaid: false,
    pets: [{ type: 'SENIOR_CAT', name: 'Oliver' }],
    owner: { firstName: 'Chen', lastName: 'L', averageRating: 4.9, totalSits: 6 },
    isNew: true, isLowApplications: true, matchScore: 94,
    currentApplicants: 0, maxApplications: 10,
  },
  {
    id: '6',
    title: 'Long Beach family home — 3 dogs need walks',
    city: 'Long Beach', state: 'CA', country: 'US',
    startDate: '2026-05-10', endDate: '2026-06-10',
    photos: ['https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=70'],
    type: 'LONG_TERM', isPaid: false,
    pets: [
      { type: 'DOG', name: 'Bruno' },
      { type: 'DOG', name: 'Daisy' },
      { type: 'DOG', name: 'Rex'   },
    ],
    owner: { firstName: 'Tom', lastName: 'W', averageRating: 4.6, totalSits: 4 },
    isNew: false, isLowApplications: true, matchScore: 71,
    currentApplicants: 3, maxApplications: 10,
  },
  {
    id: '7',
    title: 'Hollywood Hills villa — paid sit, stunning views',
    city: 'Hollywood Hills', state: 'CA', country: 'US',
    startDate: '2026-04-15', endDate: '2026-04-22',
    photos: ['https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=70'],
    type: 'PAID', isPaid: true, price: 95, currency: 'USD',
    pets: [{ type: 'CAT', name: 'Cleo' }],
    owner: { firstName: 'Priya', lastName: 'N', averageRating: 5.0, totalSits: 11 },
    isNew: true, isLowApplications: false, matchScore: 88,
    currentApplicants: 4, maxApplications: 10,
  },
  {
    id: '8',
    title: 'Arroyo Grande ranch — horses & dogs welcome',
    city: 'Arroyo Grande', state: 'CA', country: 'US',
    startDate: '2026-03-15', endDate: '2026-04-03',
    photos: ['https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=70'],
    type: 'FREE', isPaid: false,
    pets: [
      { type: 'DOG',      name: 'Duke' },
      { type: 'LIVESTOCK', name: 'Thunder' },
    ],
    owner: { firstName: 'Kate', lastName: 'S', averageRating: 4.8, totalSits: 7 },
    isNew: false, isLowApplications: true, matchScore: 73,
    currentApplicants: 2, maxApplications: 10,
  },
]
