export const MOCK_LISTINGS = [
  {
    id: '1',
    title: 'Beachside bungalow with two cats',
    city: 'Redondo Beach',
    state: 'CA',
    country: 'US',
    sitType: 'FREE',
    homeType: 'HOUSE',
    startDate: '2026-03-15',
    endDate: '2026-04-10',
    photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=70'],
    pets: [{ type: 'CAT', name: 'Cleo' }, { type: 'CAT', name: 'Leo' }],
    owner: { firstName: 'Sandra', lastName: 'D', avatar: 'https://randomuser.me/api/portraits/women/44.jpg', averageRating: 4.9, totalReviews: 12 },
    applicationCount: 3,
    maxApplications: 10,
    matchScore: 94,
    hasWifi: true,
    hasPool: false,
    hasParking: true,
    isBoosted: false,
  },
  {
    id: '2',
    title: 'Two golden retrievers in Lexington',
    city: 'Lexington',
    state: 'KY',
    country: 'US',
    sitType: 'PAID',
    homeType: 'HOUSE',
    startDate: '2026-03-10',
    endDate: '2026-04-12',
    dailyRate: 85,
    photos: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&q=70'],
    pets: [{ type: 'DOG', name: 'Buddy' }, { type: 'DOG', name: 'Max' }],
    owner: { firstName: 'Michael', lastName: 'K', avatar: null, averageRating: 4.8, totalReviews: 6 },
    applicationCount: 1,
    maxApplications: 10,
    matchScore: 88,
    hasWifi: true,
    hasPool: false,
    hasParking: true,
    isBoosted: true,
  },
  {
    id: '3',
    title: 'SF apartment with two cats',
    city: 'San Francisco',
    state: 'CA',
    country: 'US',
    sitType: 'FREE',
    homeType: 'APARTMENT',
    startDate: '2026-04-01',
    endDate: '2026-04-14',
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=70'],
    pets: [{ type: 'CAT', name: 'Luna' }],
    owner: { firstName: 'Ali', lastName: 'B', avatar: null, averageRating: 5.0, totalReviews: 8 },
    applicationCount: 8,
    maxApplications: 10,
    matchScore: 91,
    hasWifi: true,
    hasPool: false,
    hasParking: false,
    isBoosted: false,
  },
  {
    id: '4',
    title: 'Malibu villa with ocean views',
    city: 'Malibu',
    state: 'CA',
    country: 'US',
    sitType: 'PAID',
    homeType: 'VILLA',
    startDate: '2026-05-01',
    endDate: '2026-05-21',
    dailyRate: 150,
    photos: ['https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=600&q=70'],
    pets: [],
    owner: { firstName: 'James', lastName: 'W', avatar: 'https://randomuser.me/api/portraits/men/55.jpg', averageRating: 4.7, totalReviews: 4 },
    applicationCount: 5,
    maxApplications: 8,
    matchScore: 79,
    hasWifi: true,
    hasPool: true,
    hasParking: true,
    isBoosted: true,
  },
  {
    id: '5',
    title: 'Austin farmhouse & 3 rescue dogs',
    city: 'Austin',
    state: 'TX',
    country: 'US',
    sitType: 'FREE',
    homeType: 'RURAL',
    startDate: '2026-03-20',
    endDate: '2026-04-05',
    photos: ['https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=600&q=70'],
    pets: [{ type: 'DOG', name: 'Rosie' }, { type: 'DOG', name: 'Bear' }, { type: 'DOG', name: 'Scout' }],
    owner: { firstName: 'Emma', lastName: 'R', avatar: 'https://randomuser.me/api/portraits/women/62.jpg', averageRating: 4.95, totalReviews: 19 },
    applicationCount: 6,
    maxApplications: 10,
    matchScore: 85,
    hasWifi: true,
    hasPool: false,
    hasParking: true,
    isBoosted: false,
  },
]

export const PET_ICONS: Record<string, string> = {
  DOG: '🐕', CAT: '🐈', RABBIT: '🐇', BIRD: '🦜',
  FISH: '🐠', SMALL_PET: '🐹', REPTILE: '🦎',
  POULTRY: '🐓', LIVESTOCK: '🐄',
}

export const SIT_TYPE_COLORS: Record<string, string> = {
  FREE:      '#10B981',
  PAID:      '#F59E0B',
  VACANT:    '#5BA4A4',
  LONG_TERM: '#3B82F6',
  PET_ONLY:  '#8B5CF6',
}

export const SIT_TYPE_LABELS: Record<string, string> = {
  FREE:      'Free exchange',
  PAID:      'Paid sit',
  VACANT:    'Vacant sit',
  LONG_TERM: 'Long-term',
  PET_ONLY:  'Pet-only',
}
